import Head from 'next/head'
import React from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/mvp.css@1.12/mvp.css" /> 
      </Head>
      <main>
        <form onSubmit={onSubmit}>
          <label htmlFor='username'>UserName</label>
          <input type="text" id="username" name="username" placeholder='username' style={{width:'50%'}}/>
          <label htmlFor='password'>PassWord</label>
          <input type="password" id="password" name="password" placeholder='password' />
          <input type="submit" value="로그인!" />
        </form>
      </main>
    </>
  )
}
